#!/bin/bash
# startup for dependencies

#docker pull redis
#docker pull ghcr.io/ggerganov/whisper.cpp:main


#docker run -d -p 6379:6379 redis
#docker run -d -p 8080:8080 --network=host --device=/dev/kfd --device=/dev/dri --group-add=video --ipc=host --cap-add=SYS_PTRACE --security-opt seccomp=unconfined ghcr.io/ggerganov/whisper.cpp:main /app/build/bin/whisper-server -m /app/models/ggml-base.en.bin

#nohup poetry run python whisper_worker.py &

nohup poetry run python derfbot.py &
#python derfbot.py &
#nohup poetry run watchmedo auto-restart -p "*.py" -R python -- derfbot.py &
#docker run -d -p 6379:6379 redis
