#!/usr/bin/env python3

import argparse
import logging
import os
import sys
import tempfile
import time

import numpy as np
import soundfile as sf
from pydub import AudioSegment

try:
    import resource  # unix only
except Exception:  # pragma: no cover
    resource = None


logger = logging.getLogger("kokoro_test")


def _max_rss_mb() -> float | None:
    if resource is None:
        return None
    # ru_maxrss is KB on Linux
    try:
        return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024.0
    except Exception:
        return None


def synthesize_kokoro_to_wav(*, text: str, voice: str, wav_path: str) -> None:
    from kokoro import KPipeline

    pipeline = KPipeline(lang_code="a")
    generator = pipeline(text, voice)

    audio_segments = []
    for _, _, audio in generator:
        audio_segments.append(audio)

    if not audio_segments:
        raise RuntimeError("No audio generated by kokoro")

    full_audio = np.concatenate(audio_segments)
    sf.write(wav_path, full_audio, 24000)


def convert_wav_to_opus(*, wav_path: str, opus_path: str, bitrate: str = "128k") -> None:
    audio_segment = AudioSegment.from_wav(wav_path)
    audio_segment.export(opus_path, format="opus", parameters=["-b:a", bitrate])


def main() -> int:
    parser = argparse.ArgumentParser(description="Standalone Kokoro TTS smoke test")
    parser.add_argument(
        "--text",
        default="Hello. This is a Kokoro text to speech smoke test.",
        help="Text to synthesize",
    )
    parser.add_argument(
        "--voice",
        default="am_adam",
        help="Kokoro voice id (e.g. am_adam, af_nicole)",
    )
    parser.add_argument(
        "--out",
        default="/home/j/dorf/client/output/kokoro_test.wav",
        help="Output WAV path",
    )
    parser.add_argument(
        "--opus",
        default=None,
        help="Optional OPUS output path. If provided, converts WAV to OPUS.",
    )
    parser.add_argument(
        "--bitrate",
        default="128k",
        help="OPUS bitrate (e.g. 96k, 128k)",
    )
    parser.add_argument(
        "--device",
        choices=["auto", "cpu", "gpu"],
        default="auto",
        help="Device selection. 'gpu' attempts ROCm/CUDA via torch; 'cpu' disables GPU visibility.",
    )
    parser.add_argument(
        "--gpu",
        default=None,
        help="GPU index (e.g. 0). Sets HIP_VISIBLE_DEVICES/CUDA_VISIBLE_DEVICES.",
    )
    parser.add_argument(
        "--repeat",
        type=int,
        default=1,
        help="Repeat N times to detect flakiness/timeouts",
    )

    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s - %(message)s",
    )

    # IMPORTANT: env vars must be set BEFORE importing torch/kokoro.
    if args.device == "cpu":
        os.environ.setdefault("CUDA_VISIBLE_DEVICES", "")
        os.environ.setdefault("HIP_VISIBLE_DEVICES", "")
        os.environ.setdefault("ROCR_VISIBLE_DEVICES", "")
        logger.info("Device=cpu (GPU visibility disabled)")
    elif args.device == "gpu":
        if args.gpu is not None:
            os.environ["CUDA_VISIBLE_DEVICES"] = str(args.gpu)
            os.environ["HIP_VISIBLE_DEVICES"] = str(args.gpu)
            os.environ["ROCR_VISIBLE_DEVICES"] = str(args.gpu)
            logger.info("Device=gpu (forcing visible GPU index=%s)", args.gpu)
        else:
            logger.info("Device=gpu (default visible GPUs)")
    else:
        logger.info("Device=auto (no visibility overrides)")

    # Print torch info to confirm whether GPU is actually visible.
    try:
        import torch

        logger.info("torch=%s hip=%s", getattr(torch, "__version__", None), getattr(torch.version, "hip", None))
        logger.info("torch.cuda.is_available=%s device_count=%s", torch.cuda.is_available(), torch.cuda.device_count())
        for idx in range(torch.cuda.device_count()):
            try:
                logger.info("cuda[%s]=%s", idx, torch.cuda.get_device_name(idx))
            except Exception as e:
                logger.info("cuda[%s]=<error %s>", idx, e)
    except Exception as e:
        logger.info("torch import/device probe failed: %s", e)

    os.makedirs(os.path.dirname(args.out), exist_ok=True)

    logger.info("Starting Kokoro test voice=%s repeat=%s", args.voice, args.repeat)
    logger.info("Text len=%s", len(args.text))

    for i in range(1, args.repeat + 1):
        wav_path = args.out
        if args.repeat > 1:
            root, ext = os.path.splitext(args.out)
            wav_path = f"{root}.{i}{ext or '.wav'}"

        t0 = time.monotonic()
        rss0 = _max_rss_mb()

        logger.info("Run %s/%s: synthesizing -> %s", i, args.repeat, wav_path)
        synthesize_kokoro_to_wav(text=args.text, voice=args.voice, wav_path=wav_path)

        dt_ms = int((time.monotonic() - t0) * 1000)
        rss1 = _max_rss_mb()

        try:
            size = os.path.getsize(wav_path)
        except OSError:
            size = None

        logger.info("Run %s/%s: WAV written size_bytes=%s elapsed_ms=%s", i, args.repeat, size, dt_ms)
        if rss0 is not None and rss1 is not None:
            logger.info("Run %s/%s: RSS start_mb=%.1f end_mb=%.1f", i, args.repeat, rss0, rss1)

        if args.opus:
            opus_path = args.opus
            if args.repeat > 1:
                root, ext = os.path.splitext(args.opus)
                opus_path = f"{root}.{i}{ext or '.opus'}"

            logger.info("Run %s/%s: converting WAV -> OPUS (%s) -> %s", i, args.repeat, args.bitrate, opus_path)
            convert_wav_to_opus(wav_path=wav_path, opus_path=opus_path, bitrate=args.bitrate)

            try:
                opus_size = os.path.getsize(opus_path)
            except OSError:
                opus_size = None
            logger.info("Run %s/%s: OPUS written size_bytes=%s", i, args.repeat, opus_size)

    logger.info("Done")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        raise SystemExit(130)
    except Exception:
        logger.exception("Kokoro test failed")
        raise SystemExit(1)
