import os
import tempfile
import asyncio
import logging
from concurrent.futures import ThreadPoolExecutor
from pydub import AudioSegment
import numpy as np
import soundfile as sf

from bot.processing import redis_client
from bot.workers.stop_flags import stop_requested
from bot.constants import (
    DERF_AUDIO_QUEUE,
    DERF_PLAYBACK_QUEUE,
    NIC_AUDIO_QUEUE,
    NIC_PLAYBACK_QUEUE,
    TTS_VOICE,
    TTS_VOICE_NICOLE,
)

logger = logging.getLogger(__name__)

# Kokoro + audio conversion get a dedicated executor so they can't starve
# (or be starved by) redis ops and capture flushes on the default pool.
_TTS_EXECUTOR = ThreadPoolExecutor(max_workers=2, thread_name_prefix="tts")

# KPipeline loads the full model; building one per TTS line costs seconds per
# message. Cache per voice — each persona's audio worker is the only user of
# its own voice's pipeline, so instances are never shared across threads.
_KOKORO_PIPELINES = {}


def _configure_kokoro_device() -> None:
    """IMPORTANT: Kokoro uses torch. On some hosts torch may try to use
    ROCm/CUDA and hard-abort if the GPU arch isn't supported. Default to CPU
    unless explicitly enabled via env vars. Idempotent."""
    kokoro_device = os.getenv("KOKORO_DEVICE", "cpu").strip().lower()
    kokoro_gpu = os.getenv("KOKORO_GPU")

    if kokoro_device != "gpu":
        os.environ.setdefault("CUDA_VISIBLE_DEVICES", "")
        os.environ.setdefault("HIP_VISIBLE_DEVICES", "")
        os.environ.setdefault("ROCR_VISIBLE_DEVICES", "")
    else:
        if kokoro_gpu:
            os.environ["CUDA_VISIBLE_DEVICES"] = str(kokoro_gpu)
            os.environ["HIP_VISIBLE_DEVICES"] = str(kokoro_gpu)
            os.environ["ROCR_VISIBLE_DEVICES"] = str(kokoro_gpu)

    # misaki's espeak-ng fallback (used for out-of-vocabulary words) needs
    # phonemizer to find the espeak-ng library; espeakng-loader ships it but
    # misaki only auto-wires it on mac/windows. Without this, uncommon words
    # produce None phonemes and kokoro crashes with 'NoneType + str'.
    try:
        import espeakng_loader

        os.environ.setdefault(
            "PHONEMIZER_ESPEAK_LIBRARY", espeakng_loader.get_library_path()
        )
        os.environ.setdefault(
            "PHONEMIZER_ESPEAK_DATA_PATH", espeakng_loader.get_data_path()
        )
    except ImportError:
        logger.warning("espeakng-loader not installed; espeak fallback disabled.")


def get_kokoro_pipeline(voice: str):
    _configure_kokoro_device()
    if voice not in _KOKORO_PIPELINES:
        from kokoro import KPipeline

        logger.info("audio_worker.kokoro_init voice=%s", voice)
        _KOKORO_PIPELINES[voice] = KPipeline(lang_code="a")  # english
    return _KOKORO_PIPELINES[voice]


def process_kokoro_audio(line_text, voice, output_wav):
    """Sync function to handle kokoro TTS generation and file writing."""
    try:
        pipeline = get_kokoro_pipeline(voice)
        generator = pipeline(line_text, voice)
        audio_segments = []
        for _, _, audio in generator:
            audio_segments.append(audio)

        if not audio_segments:
            raise RuntimeError("No audio generated by kokoro")

        full_audio = np.concatenate(audio_segments)
        sf.write(output_wav, full_audio, 24000)
    except Exception as e:
        logger.error(f"Kokoro processing failed: {str(e)}")
        raise


def convert_wav_to_opus(wav_path, opus_path):
    """Sync function to convert WAV to OPUS."""
    audio_segment = AudioSegment.from_wav(wav_path)
    audio_segment.export(opus_path, format="opus", parameters=["-b:a", "128k"])


async def audio_task(queue_name, playback_queue_name, tts_voice, bot_instance):
    # Repo-root relative by default; override for deploys that run elsewhere.
    output_dir = os.getenv("AUDIO_OUTPUT_DIR", "output")
    os.makedirs(output_dir, exist_ok=True)
    loop = asyncio.get_event_loop()  # Reuse the same event loop
    logger.info(
        "audio_worker.start queue=%s playback_queue=%s voice=%s output_dir=%s",
        queue_name,
        playback_queue_name,
        tts_voice,
        output_dir,
    )
    while True:
        try:
            task_data = await loop.run_in_executor(None, redis_client.rpop, queue_name)

            if not task_data:
                await asyncio.sleep(1)
                continue

            logger.info(
                "audio_worker.dequeue queue=%s playback_queue=%s bytes=%s",
                queue_name,
                playback_queue_name,
                len(task_data) if isinstance(task_data, str) else -1,
            )

            unique_id, line_number, line_text = task_data.split("|", 2)

            # If a recent stop/shutup was issued for this channel, drop pending speech.
            persona = "nic" if queue_name == NIC_AUDIO_QUEUE else "derf"
            if await stop_requested(bot_instance, persona):
                logger.info(
                    "audio_worker.dropped_due_to_stop unique_id=%s persona=%s queue=%s",
                    unique_id,
                    persona,
                    queue_name,
                )
                continue

            if bot_instance.voice_clients and bot_instance.voice_clients[0].channel:
                channel = bot_instance.voice_clients[0].channel
                member_count = len(channel.members)
                # Both bots sit in the channel; counting `member_count - 1`
                # assumed one bot and reported one too many humans.
                num_users = sum(1 for m in channel.members if not m.bot)
            else:
                channel = None
                member_count = 0
                num_users = 0

            if num_users < 1:
                logger.info(
                    "audio_worker.skip_no_humans unique_id=%s users=%s member_count=%s channel=%s queue=%s",
                    unique_id,
                    num_users,
                    member_count,
                    getattr(channel, "name", None),
                    queue_name,
                )
                continue

            # Ensure unique artifacts per request to avoid cross-talk / overwrites.
            wav_path = os.path.join(output_dir, f"{unique_id}-{line_number}.wav")

            try:
                await loop.run_in_executor(
                    _TTS_EXECUTOR, process_kokoro_audio, line_text, tts_voice, wav_path
                )
            except Exception as e:
                logger.exception(
                    "audio_worker.kokoro_error unique_id=%s voice=%s err=%s",
                    unique_id,
                    tts_voice,
                    e,
                )
                continue

            if not os.path.exists(wav_path):
                logger.error(f"WAV missing: {wav_path}")
                continue

            # Convert to OPUS
            with tempfile.NamedTemporaryFile(delete=False, suffix=".opus") as tmp_opus:
                opus_path = tmp_opus.name

                try:
                    await loop.run_in_executor(
                        _TTS_EXECUTOR, convert_wav_to_opus, wav_path, opus_path
                    )
                except Exception:
                    # Don't leak the empty temp file if conversion failed.
                    try:
                        if os.path.exists(opus_path):
                            os.remove(opus_path)
                    except OSError:
                        logger.warning(
                            "audio_worker.opus_cleanup_failed opus_path=%s",
                            opus_path,
                            exc_info=True,
                        )
                    raise

                # Best-effort cleanup of intermediate wav
                try:
                    if os.path.exists(wav_path):
                        os.remove(wav_path)
                except Exception:
                    pass

                # Re-check stop before enqueuing playback (covers in-flight TTS).
                if await stop_requested(bot_instance, persona):
                    logger.info(
                        "audio_worker.skip_enqueue_due_to_stop unique_id=%s persona=%s opus_path=%s",
                        unique_id,
                        persona,
                        opus_path,
                    )
                    try:
                        if os.path.exists(opus_path):
                            os.remove(opus_path)
                    except OSError:
                        logger.warning(
                            "audio_worker.opus_cleanup_failed opus_path=%s",
                            opus_path,
                            exc_info=True,
                        )
                    continue

                # Push to playback queue without blocking
                await loop.run_in_executor(
                    None,
                    redis_client.lpush,
                    playback_queue_name,
                    f"{unique_id}|{opus_path}",
                )

                logger.info(
                    "audio_worker.enqueued_playback unique_id=%s playback_queue=%s opus_path=%s",
                    unique_id,
                    playback_queue_name,
                    opus_path,
                )

        except Exception as e:
            logger.exception("audio_worker.loop_error queue=%s err=%s", queue_name, e)
            await asyncio.sleep(1)


async def nic_audio_task(bot):
    await audio_task(
        queue_name=NIC_AUDIO_QUEUE,
        playback_queue_name=NIC_PLAYBACK_QUEUE,
        tts_voice=TTS_VOICE_NICOLE,
        bot_instance=bot,
    )


async def derf_audio_task(bot):
    await audio_task(
        queue_name=DERF_AUDIO_QUEUE,
        playback_queue_name=DERF_PLAYBACK_QUEUE,
        tts_voice=TTS_VOICE,
        bot_instance=bot,
    )
