"""Kokoro TTS provider (the current engine behind the Discord voice pipeline).

Moved verbatim-ish from bot/workers/audio_worker.py so the engine is a
pluggable provider instead of being welded into the worker.
"""
import logging
import os
import threading

import numpy as np
import soundfile as sf

from bot.tts.base import TTSProvider, register_tts

logger = logging.getLogger(__name__)

# KPipeline loads the full model; building one per TTS line costs seconds per
# message. Cache per voice — each persona's audio worker is the only user of
# its own voice's pipeline, so instances are never shared across threads.
_KOKORO_PIPELINES = {}

# A KPipeline is single-user: the persona audio workers used to be the only
# callers and each voice had exactly one sequential consumer. The pet path
# (response worker) now synthesizes with TTS_VOICE in the same process as
# derf's audio worker — same voice, same pipeline — so generation per voice
# is serialized with a lock instead of racing two threads on one pipeline.
_VOICE_LOCKS = {}
_VOICE_LOCKS_GUARD = threading.Lock()


def _voice_lock(voice: str) -> threading.Lock:
    with _VOICE_LOCKS_GUARD:
        return _VOICE_LOCKS.setdefault(voice, threading.Lock())


def _configure_kokoro_device() -> None:
    """IMPORTANT: Kokoro uses torch. On some hosts torch may try to use
    ROCm/CUDA and hard-abort if the GPU arch isn't supported. Default to CPU
    unless explicitly enabled via env vars. Idempotent."""
    kokoro_device = os.getenv("KOKORO_DEVICE", "cpu").strip().lower()
    kokoro_gpu = os.getenv("KOKORO_GPU")

    if kokoro_device != "gpu":
        os.environ.setdefault("CUDA_VISIBLE_DEVICES", "")
        os.environ.setdefault("HIP_VISIBLE_DEVICES", "")
        os.environ.setdefault("ROCR_VISIBLE_DEVICES", "")
    else:
        if kokoro_gpu:
            os.environ["CUDA_VISIBLE_DEVICES"] = str(kokoro_gpu)
            os.environ["HIP_VISIBLE_DEVICES"] = str(kokoro_gpu)
            os.environ["ROCR_VISIBLE_DEVICES"] = str(kokoro_gpu)

    # misaki's espeak-ng fallback (used for out-of-vocabulary words) needs
    # phonemizer to find the espeak-ng library; espeakng-loader ships it but
    # misaki only auto-wires it on mac/windows. Without this, uncommon words
    # produce None phonemes and kokoro crashes with 'NoneType + str'.
    try:
        import espeakng_loader

        os.environ.setdefault(
            "PHONEMIZER_ESPEAK_LIBRARY", espeakng_loader.get_library_path()
        )
        os.environ.setdefault(
            "PHONEMIZER_ESPEAK_DATA_PATH", espeakng_loader.get_data_path()
        )
    except ImportError:
        logger.warning("espeakng-loader not installed; espeak fallback disabled.")


def _get_kokoro_pipeline(voice: str):
    _configure_kokoro_device()
    if voice not in _KOKORO_PIPELINES:
        from kokoro import KPipeline

        logger.info("tts.kokoro_init voice=%s", voice)
        _KOKORO_PIPELINES[voice] = KPipeline(lang_code="a")  # english
    return _KOKORO_PIPELINES[voice]


@register_tts
class KokoroProvider(TTSProvider):
    name = "kokoro"

    def synthesize(self, text: str, voice: str, output_wav: str) -> None:
        """Blocking: kokoro generation + wav write (16-bit PCM so Godot's
        AudioStreamWAV can load it too — Discord's opus conversion reads it
        the same). Concurrent callers with the same voice serialize here."""
        try:
            with _voice_lock(voice):
                pipeline = _get_kokoro_pipeline(voice)
                generator = pipeline(text, voice)
                audio_segments = []
                for _, _, audio in generator:
                    audio_segments.append(audio)

                if not audio_segments:
                    raise RuntimeError("No audio generated by kokoro")

                full_audio = np.concatenate(audio_segments)
                sf.write(output_wav, full_audio, 24000, subtype="PCM_16")
        except Exception as e:
            logger.error(f"Kokoro processing failed: {str(e)}")
            raise
